---
name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  - push
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup sv4git
        run: |
          curl -s https://api.github.com/repos/bvieira/sv4git/releases/latest | jq -r '.assets[] | select(.browser_download_url | contains("linux")) | .browser_download_url' | wget -O /tmp/sv4git.tar.gz -qi - \
            && tar -C /usr/local/bin -xzf /tmp/sv4git.tar.gz
      - name: Create tag
        id: create-tag
        run: | 
          git sv nv
          VERSION=$(git sv cv)
          echo "::set-output name=tag::v$VERSION"
      - name: Create release notes
        run: |
          git sv rn -t "${{ needs.tag.outputs.tag }}"
    outputs:
      tag: ${{ steps.create-tag.outputs.tag }}
...
